services:
  app:
    build: .
    container_name: family_bot
    depends_on:
      - db
    environment:  
      - DATABASE_URL=postgresql+asyncpg://family_bot:11235813@db:5432/family_bot
    ports:
      - "55582:55582"
    volumes:
      - .:/app

  db:
    image: postgres
    container_name: db_family_bot
    environment:
      POSTGRES_DB: family_bot
      POSTGRES_USER: family_bot 
      POSTGRES_PASSWORD: 11235813
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: {}
